[tool.poetry]
name = "burla"
version = "0.8.14"
description = "Scale your program across 1000s of computers with one line of code."
authors = ["Jake Zuliani <jake@burla.dev>"]


[tool.poetry.dependencies]
python = ">=3.10,<=3.12"
fire = "^0.5.0"
appdirs = "^1.4.4"
requests = "^2.32.3"
yaspin = "^2.5.0"
cloudpickle = "^3.0.0"
tblib = "^3.0.0"
tomli = "^2.0.1"
ipython = "^7.0.0"
google-cloud-firestore = "2.19.0"

[tool.poetry.scripts]
burla = "burla.__init__:init_cli"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pytest = "^7.4.2"
docker = "^7.1.0"
jupyterlab = "^4.3.1"

# indicate if in dev,
# cannot use env variable or, once installed (on a developer pc), pkg would think it's in dev
# package checks for this tag in this file inside `burla/__init__.py`
[tool.burla.config]
in_dev = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
