[tool.poetry]
name = "burla"
version = "1.1.0"
description = "Scale your program across 1000s of computers with one line of code."
authors = ["Jake Zuliani <jake@burla.dev>"]


[tool.poetry.dependencies]
python = ">=3.10,<4.0"
fire = ">=0.7"
appdirs = ">=1.4"
requests = ">=2.32"
yaspin = ">=2.5"
cloudpickle = ">=3.0"
tblib = ">=3.0"
tomli = ">=2.0"
ipython = ">=7.0"
google-cloud-firestore = ">=2.20"
aiohttp = ">=3.11.14"
google-cloud-run = ">=0.10"
six = "^1.17.0"

[tool.poetry.scripts]
burla = "burla.__init__:init_cli"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pytest = "^7.4.2"
jupyterlab = "^4.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
