[tool.poetry]
name = "burla"
version = "1.0.12"
description = "Scale your program across 1000s of computers with one line of code."
authors = ["Jake Zuliani <jake@burla.dev>"]


[tool.poetry.dependencies]
python = ">=3.10"
fire = "^0.5.0"
appdirs = "^1.4.4"
requests = "^2.32.3"
yaspin = "^2.5.0"
cloudpickle = "^3.0.0"
tblib = "^3.0.0"
tomli = "^2.0.1"
ipython = "^7.0.0"
google-cloud-firestore = "^2.20.1"
aiohttp = "^3.11.14"
google-cloud-run = "^0.10.17"

[tool.poetry.scripts]
burla = "burla.__init__:init_cli"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pytest = "^7.4.2"
jupyterlab = "^4.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
